version: "3"
services:
  odoo:
    container_name: o14_src
    image: odoo:14.0
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./modules:/mnt/extra-addons/
      - ./odoo_conf:/etc/odoo
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    container_name: o14_db
    image: postgres:12.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
